In [3]:
import numpy as np
import pandas as pd

In [4]:
a = np.array([10,20,30])

In [5]:
a[0:2]

array([10, 20])

In [6]:
pessoas = pd.read_excel('caso_estudo.xlsx', sheet_name='pessoas')
pessoas

id               nome sexo  idade
0       1      Lavinia Sousa    F     18
1       2       Caio Pereira    M     28
2       3      Júlio Azevedo    M     32
3       4    Sarah Goncalves    F     49
4       5  Gabrielle Martins    F     27
..    ...                ...  ...    ...
995   996     Ágatha Ribeiro    F     31
996   997     Laura Oliveira    F     23
997   998      Lara Oliveira    F     24
998   999       Julian Cunha    M     43
999  1000    Gustavo Barbosa    M     23

[1000 rows x 4 columns]

In [7]:
pessoas = np.array(pd.read_excel('caso_estudo.xlsx', sheet_name='pessoas'))
pessoas

array([[1, 'Lavinia Sousa', 'F', 18],
       [2, 'Caio Pereira', 'M', 28],
       [3, 'Júlio Azevedo', 'M', 32],
       ...,
       [998, 'Lara Oliveira', 'F', 24],
       [999, 'Julian Cunha', 'M', 43],
       [1000, 'Gustavo Barbosa', 'M', 23]], dtype=object)

In [8]:
np.sum(pessoas[:,3])

33909

In [9]:
pessoas[pessoas[:,2]=='M']

array([[2, 'Caio Pereira', 'M', 28],
       [3, 'Júlio Azevedo', 'M', 32],
       [6, 'Felipe Almeida', 'M', 31],
       ...,
       [994, 'Eduardo Costa', 'M', 34],
       [999, 'Julian Cunha', 'M', 43],
       [1000, 'Gustavo Barbosa', 'M', 23]], dtype=object)

In [10]:
    import numpy as np
    matriz = np.array([[1,2,3],[10,20,30],[5,15,35]])

In [11]:
matriz[np.any(matriz>10,0)]

array([[10, 20, 30],
       [ 5, 15, 35]])